version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: toracoya/petstore-db:0.0.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: wait for db
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s

      # run tests!
      - run: cat /dev/null | sbt test:test
